version: "3.9"
services:
  postgres-pm:
    image: postgres:14
    restart: "no"
    container_name: "postgres-pm"
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
        - POSTGRES_USER=passman
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=PASSWORD_MANAGER
  mongodb-pm:
    image: mongo:4.4.10
    restart: "no"
    container_name: mongodb-pm
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbUser
      MONGO_INITDB_ROOT_PASSWORD: mongodbPassword
      MONGODB_USERNAME: mongodbUser
      MONGODB_PASSWORD: mongodbPassword
      MONGO_INITDB_DATABASE: password_manager
networks:
  pm-network:
    driver: bridge
