version: "3.9"
services:
  postgres-pm:
    image: postgres:14
    restart: "no"
    container_name: "postgres-pm"
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: 4G
    environment:
        - POSTGRES_USER=passman
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=PASSWORD_MANAGER
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
networks:
  pm-network:
    driver: bridge
